version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: erp-max-postgres
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erp_max_tenant
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - erp-max-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: erp-max-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: erp_user
      RABBITMQ_DEFAULT_PASS: erp_pass
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - erp-max-network

  redis:
    image: redis:7
    container_name: erp-max-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - erp-max-network

  graphql-gateway:
    build:
      context: ./graphql-gateway
      dockerfile: Dockerfile
    container_name: erp-max-graphql-gateway
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erp_max
      RABBITMQ_URL: amqp://erp_user:erp_pass@rabbitmq:5672
      REDIS_HOST: redis
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - erp-max-network

  tenant-svc:
    build:
      context: ./tenant-svc
      dockerfile: Dockerfile
    container_name: erp-max-tenant-svc
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erp_max
      RABBITMQ_URL: amqp://erp_user:erp_pass@rabbitmq:5672
      REDIS_HOST: redis
    ports:
      - "3001:3001"  
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - erp-max-network

  erp-svc:
    build:
      context: ./erp-svc
      dockerfile: Dockerfile
    container_name: erp-max-erp-svc
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erp_max
      RABBITMQ_URL: amqp://erp_user:erp_pass@rabbitmq:5672
      REDIS_HOST: redis
    ports:
      - "3002:3002"  
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - erp-max-network

  erp-front:
    build:
      context: ./erp-front
      dockerfile: Dockerfile
    container_name: erp-max-erp-front
    ports:
      - "4000:4200"
    volumes:
      - ./erp-front:/app
      - erp-front-node-modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - erp-max-network

networks:
  erp-max-network:
    driver: bridge
    
volumes:
  erp-front-node-modules:    
